# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[dependency-groups]
integration = [
  "allure-pytest>=2.8.18",
  "allure-pytest-collection-report @ git+https://github.com/canonical/data-platform-workflows@v24.0.0#subdirectory=python/pytest_plugins/allure_pytest_collection_report",
  "httpx[http2]==0.28.1",
  "jinja2==3.1.6",
  "jubilant==1.6.1",
  "juju==3.6.1.3",
  "protobuf==6.33.1",
  "playwright==1.56.0",
  "pytest",
  "pytest-asyncio",
  "pytest-operator",
  "websockets<16",
]

[tool.uv]
package = false

