name: Publish spoe-auth snap to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - spoe_auth_snap/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.1
    - uses: snapcore/action-build@v1.3.0
      id: build
      with:
        path: ./spoe_auth_snap
    - uses: snapcore/action-publish@v1.2.0
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
