name: Update Terraform documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    name: Update Terraform documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: terraform/charm,terraform/product
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: "chore(docs): Update Terraform documentation"

      # terraform-docs/gh-actions changes the permissions of repository files
      - name: Change file ownership
        run: sudo chown $USER -R .

      - name: Create pull request for main branch
        uses: canonical/create-pull-request@main
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(docs): Update Terraform documentation"
          branch-name: terraform-docs
          title: "chore(docs): Update Terraform documentation"
          body: "Update Terraform documentation in terraform/charm,terraform/product."
          upsert: true
          ignore-no-changes: true
          auto-merge: true
