name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: true
      self-hosted-runner-image: "noble"
      working-directory: ./haproxy-operator
      with-uv: true
  haproxy-spoe-auth-operator:
    name: Unit tests for the haproxy-spoe-auth-operator charm
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: true
      self-hosted-runner-image: "noble"
      python-version: 3.12
      working-directory: ./haproxy-spoe-auth-operator
      with-uv: True
